stage: dev
server:
  bind: 0.0.0.0
  port: 3001
services:
  - .sandbox/services/*/bacre.yaml
users:
  # kim:possible
  - kim:$2y$05$O6pLpHgLgQV1PSlzzLGGNuMp205RBZyqfdHO0XGoJ4EmeTL9ZaReO
envsets:
  demo:
    RESTIC_PASSWORD: demo
  # for the one service whose repository should not open
  demo-wrong-password:
    RESTIC_PASSWORD: not-the-password
sandbox: .sandbox
tmpDir: .sandbox/tmp
backends:
  restic:
    cacheDir: .sandbox/cache
    stagingDir: .sandbox/staging
